### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by DillFrescott** [with-labs/popspace#14]
Error: ENOENT: no such file or directory, stat '/usr/src/app/noodle/build/index.html'

**Comment by a-type** [comment]
That would indicate that the frontend client files have not been built. "ENOENT" is an OS error code which stands for "Error: No Entry" which means the file was not found at the location. Since the frontend is transpiled, the build step needs to be run before the source files are written.

The (confusingly named) `yarn precontainerize` script will run all builds for you, which should produce the necessary files.

If you're running in Docker I recommend pulling our pre-built Docker image which should already have everything in place: `docker pull ghcr.io/with-labs/popspace:latest`

**Comment by DillFrescott** [comment]
Thank you so much for the clarification!
