### ISSUE TITLE
Couple issues

### ISSUE THREAD

**Issue by dillfrescott** [with-labs/popspace#18]
The notepad does not load it just spins forever. Also when I upload a file it displays as just the picture name and not the actual jpg file image

**Comment by a-type** [comment]
Is there any error output from any of the server processes in your container?

**Comment by dillfrescott** [comment]
Ah, I dont believe there was any errors of any sort. Id have to test it again but I don't remember seeing any

**Comment by jaderms** [comment]
I also experience both of these issues. The first one, where the spinner keeps spinning indefinitely, only occurs in Google Chrome. If I remove the widget and then restore it, it starts working. A page reload works too.

Regarding the second problem, I managed to solve it by modifying the file noodle-api/src/lib/files.js. I added 'async/await' to the metadata retrieval:

```javascript
getFileMetadata: async (fileId) => {
  const base = await shared.db.prisma.fileUpload.findUnique({ where: { id: (fileId) } })

#19

**Comment by a-type** [comment]
Sorry for not keeping up with this, but I've also been able to reproduce the notepad issue. Unfortunately the notepad is a particularly complicated widget under the hood so it may require some further intervention.

It's odd to me that your fix worked for images, since I've not had any trouble with my local testing, but you're right that that code is definitely broken.

**Comment by jaderms** [comment]
I believe I have managed to resolve the issue in the Notepad. It seems that the attempt to address the race condition wasn't fully implemented, which is why it wasn't working correctly. I have submitted my changes in PR #20.

**Comment by dillfrescott** [comment]
@jaderms Amazing!
